"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";

import { Provider } from "react-redux";
import store from '../Store/index'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Google drive clone",
//   description: "Generated by create next app",
// };

interface root {
  children: React.ReactNode
}

/* This is mostly intended for prototyping; please download the pattern and re-host for production environments. Thank you! */

/* This is mostly intended for prototyping; please download the pattern and re-host for production environments. Thank you! */

const RootLayout: React.FC<root> = ({ children }) => {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </Provider>
  );
}

export default RootLayout